- hosts: all
  
  
  tasks: 
#    - name: "Criando um arquivo no servidor"
#      shell: "echo 'escrevendo algo no servidor' >> teste.txt"

    - name: "Executa o apg-get update"
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: "Instala pacotes"
      apt: 
        name: ['nginx', 'git']
        state: latest
      become: yes
    
    - name: "add github ssh key"
      copy: >
        src=/home/ubuntu/.ssh/id_rsa
        dest=/home/ubuntu/id_rsa
        owner=ubuntu
        group=ubuntu
        mode=0600
      
    - name: clone a private repository
      git: >
        repo=git@github.com:andremarciolopes/MobEAD.git
        key_file=/home/ubuntu/id_rsa
        dest=/var/www/html/app
        accept_hostkey=yes
        force=yes
        recursive=no
