- hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www/html
    app_root: html_demo_site-main
  
  
  tasks: 
#    - name: "Criando um arquivo no servidor"
#      shell: "echo 'escrevendo algo no servidor' >> teste.txt"

    - name: "Executa o apg-get update"
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: "Instala pacotes"
      apt: 
        name: ['nginx', 'git']
        state: latest
      become: yes
    
    - name: "Adicionar a chave ssh do git"
      copy: >
        src=/home/ubuntu/.ssh/id_rsa
        dest=/home/ubuntu/id_rsa
        owner=ubuntu
        group=ubuntu
        mode=0600
      
    - name: "Clonar o repositório do git"
      git: >
        repo=git@github.com:andremarciolopes/MobEAD.git
        key_file=/home/ubuntu/id_rsa
        dest=/home/ubuntu/app
        accept_hostkey=yes
        force=yes
        recursive=no
     
    - name: Apply Nginx template
      template:
        src: /home/ubuntu/terraforms/atividade04/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx
      
    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        
   
