- hosts: all
  
  
  tasks: 
#    - name: "Criando um arquivo no servidor"
#      shell: "echo 'escrevendo algo no servidor' >> teste.txt"

    - name: "Instala pacotes"
      apt: 
        name: "nginx"
        state: latest
      become: yes      
    
    - name: "add github ssh key"
      copy: >
        src=/home/ubuntu/.ssh/id_rsa
        dest=/home/ubuntu/.ssh/id_rsa
        owner=ubutu
        group=ubuntu
        mode=0600

